### ISSUE TITLE
IEEET1 Exciter Model Issue

### ISSUE THREAD

**Issue by maguilerac** [SmarTS-Lab/OpenIPSL#116]
The translation of the IEEET1 exciter model returns the following error:

_The initialization problem is overspecified for variables of element type Real.
There are 1 too many scalar conditions.
To correct it you can
remove initial equations:
iEEET2_1.SE_Efd0 = OpenIPSL.NonElectrical.Functions.SE(iEEET2_1.Efd0, iEEET2_1.S_EE_1, iEEET2_1.S_EE_2, iEEET2_1.E_1, iEEET2_1.E_2);
iEEET2_1.Efd0 = gENROE.efd0;
(iEEET2_1.VRMAX0, iEEET2_1.VRMIN0, iEEET2_1.KE0) = OpenIPSL.Electrical.Controls.PSSE.ES.BaseClasses.calculate_dc_exciter_params (iEEET2_1.V_RMAX, iEEET2_1.V_RMIN, iEEET2_1.K_E, iEEET2_1.E_2, iEEET2_1.S_EE_2, iEEET2_1.Efd0, iEEET2_1.SE_Efd0);
iEEET2_1.VRMIN0 = -iEEET2_1.VRMAX0;_

**Comment by tinrabuzin** [comment]
@maguilerac There is an extra instruction in the `initial equation` section. Can you remove `VRMIN0 = -VRMAX0;`, try to simulate again and create a PR with the change?

**Comment by MaximeBaudette** [comment]
@tinrabuzin Thanks for the input! I'll be helping @maguilerac to prepare the PR.

**Comment by maguilerac** [comment]
@tinrabuzin Thanks Tin! I followed your suggestion and it works. I only need to remember how to do the PR. Fortunately, @MaximeBaudette has been very kind to help me with that.
