### ISSUE TITLE
Fixing Components using Sensors

### ISSUE THREAD

**Issue by MaximeBaudette** [SmarTS-Lab/OpenIPSL#13]
After merging #10 there is no longer the sensor package. The component ESST4B should be reimplemented without the sensor it is using

**Comment by MaximeBaudette** [comment]
The *Old_transformer.ThreeWinding* is also using a sensor

**Comment by tinrabuzin** [comment]
@MaximeBaudette Then we have to fix that too.

**Comment by MaximeBaudette** [comment]
The *SVC* is also using PwVoltage

**Comment by MaximeBaudette** [comment]
update for #23
