### ISSUE TITLE
Expandable bus causing problems in OM

### ISSUE THREAD

**Issue by tinrabuzin** [SmarTS-Lab/OpenIPSL#30]
I noticed that in OM for examples N44 and SevenBus, expandable bus causes the number of equations to be higher than the number of variables in the model and, thus, the systems cannot be simulated.

**Comment by tinrabuzin** [comment]
I replaced all of the expandable buses with the regular ones and the seven bus simulated with the results that are the same as the ones in Dymola.

**Comment by MaximeBaudette** [comment]
I don't know how to proceed about that... 
Because on one side, the expandable bus makes it very nice to have a good overlook of the system. 
On the other side, it prevents simulation in OM... Should we just duplicate the models and use simple buses in the duplicate model?

**Comment by tinrabuzin** [comment]
@MaximeBaudette Expendable bus works in the example from MSL so I guess this is due to our implementation. I'll investigate it a bit more.

**Comment by MaximeBaudette** [comment]
ok

**Comment by tinrabuzin** [comment]
Both N44 and SevenBus can now be simulated in OM after all of the fixes.
