### ISSUE TITLE
Wrong link in readme.md

### ISSUE THREAD

**Issue by sorrento** [SmarTS-Lab/OpenIPSL#58]
to the wiki
in the section "notice to users"
https://github.com/SmarTS-Lab/OpenIPSL/blob/master/update%20link

**Comment by MaximeBaudette** [comment]
I'm working on updating the documentation, but it has been slower than expected, sorry for the inconvenience

**Comment by lvanfretti** [comment]
I hope to have time in July also to contribute...

**Comment by sorrento** [comment]
Sorry I didn't explain well:
In the readme.md, on the section  https://github.com/SmarTS-Lab/OpenIPSL#notice-to-users
the link to the wiki there leads to a "**error 404 page not found**".
I just say, since you already have some content on the wiki, put the correct url, that is 
https://github.com/SmarTS-Lab/OpenIPSL/wiki
 That's all.

Thanks!
