### ISSUE TITLE
Wiki - Editing Footers with OpenIPSL Logo?

### ISSUE THREAD

**Issue by lvanfretti** [SmarTS-Lab/OpenIPSL#64]
@MaximeBaudette I was trying to change the logo in: [https://github.com/SmarTS-Lab/OpenIPSL/wiki/Project-and-Community](here), and all the other child pages of the wiki, but because I am not so smart I could not figure out.

Can you tell me how to do it? Or can you put the puppy logo in all the footers?

Thank you!

Luigi

**Comment by tinrabuzin** [comment]
@lvanfretti The puppy is now in the footer.
