### ISSUE TITLE
Various copyright statements still present in the development version

### ISSUE THREAD

**Issue by dietmarw** [SmarTS-Lab/OpenIPSL#89]
I though the reason for the new script that adds the copyright was to clean out the development version of all the duplicates. But the latest (versioned) development version is still full with this "noise".  Is that on purpose or simply oversight?

**Comment by MaximeBaudette** [comment]
@dietmarw 
Good remark !
Actually, now that I think about it, I would remove the noise alltogether and just place a notice on the top layer Modelica package... What an irony you are probably thinking!

**Comment by dietmarw** [comment]
Yes, that idea does sound familiar somewhat. :smirk:

**Comment by dietmarw** [comment]
Where you thinking of getting also rid of the `<!--DISCLAIMER-->` place holder at the same time? Or do you think it should stay for later release processing?

**Comment by MaximeBaudette** [comment]
Actually, if we were moving to removing all of them, I'd even remove this I think.

**Comment by MaximeBaudette** [comment]
Anyhow, now that I prepared a script to update the annotations, it's easy to use to remove all of them also :smile:

**Comment by dietmarw** [comment]
That's true, since you don't actually look out for that place holder at all.

**Comment by MaximeBaudette** [comment]
Let's keep quiet on my quick n' dirty fixes :stuck_out_tongue_winking_eye:

**Comment by dietmarw** [comment]
As part of #91, I've now added a copyright class and removed manually the local copyright statements whenever I touched a class. It would perhaps be a good idea to run your script after the merge of #91 in order to remove the remaining ones. I didn't want to touch it since it is hard coded for your machine @MaximeBaudette

**Comment by MaximeBaudette** [comment]
Oh you're right.... :disappointed: 
Terrible! I really should fix that

**Comment by janlav** [comment]
@MaximeBaudette is this addressed in your latest contributions?

**Comment by MaximeBaudette** [comment]
Yes I fixed it
