### ISSUE TITLE
2 identical CSVGN1 models?

### ISSUE THREAD

**Issue by dietmarw** [SmarTS-Lab/OpenIPSL#94]
It looks to me like:
`OpenIPSL.Electrical.Banks.CSVGN1`
and 
`OpenIPSL.Electrical.Banks.PSSE.CSVGN1`
are identical and one of them should be removed. But which one?

**Comment by tinrabuzin** [comment]
@dietmarw They are identical.  `OpenIPSL.Electrical.Banks.CSVGN1` should be removed.
