### ISSUE TITLE
Possible to rename folder "Application Examples" to "ApplicationExamples"?

### ISSUE THREAD

**Issue by dietmarw** [SmarTS-Lab/OpenIPSL#95]
Blanks in file pathes are always a pain when one wants to run scripts over a library. Yes there are workarounds but it is often a PITA. Would it be a problem to rename the folder `Application Examples` to `ApplicationExamples`?

**Comment by MaximeBaudette** [comment]
I agree with you. Just rename it in #91 if you want.
